title: Material-You-Apps
markdown: kramdown
# url: "https://teaendsacronyms.github.io/Material-You-Apps/"
# baseurl: "/Material-You-Apps"

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["LICENSE", "README.md"]
